version: '3'
services:
  ci4_banksampahpedia_container:
    container_name: ci4-banksampahpedia-container
    build:
      context: ./ # root folder docker-compose
      dockerfile: ./.docker/Dockerfile
    ports:
      - 5003:80
    volumes:
      - ./:/var/www/html/banksampahpedia/
      - ./.docker/php-custom.ini:/usr/local/etc/php/conf.d/php-custom.ini
    networks:
      - mysql-network

networks:
  mysql-network:
    external: true
